# Generated by Django 4.2.4 on 2023-12-11 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight', '0002_flights_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('number_of_stars', models.IntegerField()),
                ('has_single_rooms', models.BooleanField(default=False)),
                ('has_double_rooms', models.BooleanField(default=False)),
                ('has_deluxe_rooms', models.BooleanField(default=False)),
                ('has_suites', models.BooleanField(default=False)),
                ('has_presidential_suites', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField()),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('deluxe', 'Deluxe Room'), ('suite', 'Suite'), ('presidential_suite', 'Presidential Suite')], max_length=20)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.user')),
            ],
        ),
    ]
