# Generated by Django 4.2.4 on 2023-12-11 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('flight_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('departure_city', models.CharField(max_length=100)),
                ('arrival_city', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('airlines', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane_class', models.CharField(max_length=10)),
                ('seat_number', models.CharField(max_length=10)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flights')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.user')),
            ],
        ),
    ]
